### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by seamusmcaffrey** [Pizzaface/Alexa-Chromecast-Skill-2.0#12]
Apologies if I'm using the site features wrong by logging an issue, but it looks like I'm missing a very basic first step on this as the initial step errors out most lines. I set up an alexa to kodi install earlier and thought this would be a nice second challenge, but this one may be over my current expertise. Current issue: http://imgur.com/a/NtEBX

Let me know if you have thoughts on how to get around this; the steps seem to make enough sense but it's not asking me for input of aws keys or anything. Not sure what I'm missing. Thanks!

**Comment by LukeChannings** [comment]
Two problems that I can see:

1. You're running `aws-setup` In your home directory, not `~/Documents/x`
2. awscli is not installed

**Comment by seamusmcaffrey** [comment]
Hmm, I dragged the .sh to terminal and that's the path it gave me, but I'll play around with that. I'll install that as well and see what happens. Thanks!

**Comment by LukeChannings** [comment]
I've updated the script to change to the directory the script is in and error when pip isn't installed, which should give a clear warning and some instructions for people with the same environment as you.

**Comment by seamusmcaffrey** [comment]
Thanks a lot! Won’t be able to look again until this weekend probably, but
this is really appreciated.


On July 24, 2017 at 7:24:02 AM, Luke Channings (notifications@github.com)
wrote:

I've updated the script to change to the directory the script is in and
error when pip isn't installed, which should give a clear warning and some
instructions for people with the same environment as you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pizzaface/Alexa-Chromecast-Skill-2.0/issues/12#issuecomment-317393456>,
or mute the thread
