### ISSUE TITLE
Certain videos don't work

### ISSUE THREAD

**Issue by waxhell** [Pizzaface/Alexa-Chromecast-Skill-2.0#14]
Certain youtube videos don't work. Not 100% sure what might be causing it, but here is an example:

"Alexa Tell Chromecast to Play Single Ladies"

This references the following youtube video:
https://www.youtube.com/watch?v=4m1EFMoRFvY

I can see that the skill spawns the following:
```/usr/bin/python2 /usr/sbin/youtube-dl -g --no-check-certificate -- 4m1EFMoRFvY```

After that process is complete, I see the following python exception:

```
ERROR: Signature extraction failed: Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1035, in _decrypt_signature
    video_id, player_url, s
   File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 927, in _extract_signature_function
     raise ExtractorError('Cannot identify player %r' % player_url)
 ExtractorError: Cannot identify player u'/yts/jsbin/player-vflN55NZo/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl
  (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflN55NZo/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
```

I did try doing a pip2 --update youtube_dl to the latest version -- 2017.07.30.1, however that version does spawn a chromecast video playback instance, but nothing actually plays (including videos that previously played properly).

**Comment by rafiahmad1980** [comment]
I am facing same issue. Now none of the videos work for me. Previous most of the videos were working, some giving errors as you mentioned above. Now It just shows a chrome blue icon on the TV. Any help will be appreciated.

**Comment by LukeChannings** [comment]
Fixed with PR
