### ISSUE TITLE
Casting results only in blue Cast icon on TV display

### ISSUE THREAD

**Issue by rafiahmad1980** [Pizzaface/Alexa-Chromecast-Skill-2.0#15]
After all installation and setup, the cast worked perfectly for most of the videos through alexa. But when i killed the start.sh using Cnrl+C and tried running start.sh again, it start giving lots of python errors in some lines in many of the files. When i googled those errors, i was asked in one of the forum to upgrade youtube-dl package to the newest one. I did that. 

Afterwards, when i asked alexa to play something on chromecast, Alexa finds the video and on my command prompt, i see the youtube url for video and audio showing up. There is absolutely no error message. My TV chromecast also tried to load it. There is a blue bar goes from left to right but shows a blue chromecast icon in the middle. And this is where it gets stuck. The video/ audio not playing anymore. 

I can play video on my TV chromecast using my phone and table just fine. 

My OS is raspbian, on raspberry pi 3. 

Please let me know, how to fix it.

**Comment by rafiahmad1980** [comment]
Never mind i resolved the issue by myself. The issue was with the youtube url we were getting thought youtube-dl. With below option in "ChromecastSkill.py" file, the output was 2 different URLs, one each for video and audio file. That was causing issue with my Chromecast.

youtube-dl -g --no-check-certificate -- 

I added "-f best". The output was only 1 url, having both video and audio. This made things working again.

youtube-dl -g --no-check-certificate -f best --

**Comment by LukeChannings** [comment]
Do you mind making a PR?

**Comment by rafiahmad1980** [comment]
Hi Luke,

I am newbie to github, but a fast learner. I followed all the process to
setup the local repo and tried to create a branch, but it gave following
error:

----------------------------------------------------------------------------------------
ERROR: Permission to Pizzaface/Alexa-Chromecast-Skill-2.0.git denied to
rafiahmad1980.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
----------------------------------------------------------------------------------------

I think i need some access to your repo or let me know if you rather want
me to create my own forked repo?



With Regards,

Rafi Ahmad

**Comment by LukeChannings** [comment]
Hi Rafi,

Thanks for your efforts so far, the usual process is:

- fork this repository
- make changes in your forked version
- make a pull request back to this repository

That way we get a diff of all the changes, it can be linked to issues, etc.

It should hopefully be obvious from the GitHub interface which buttons to press, but if you get stuck don't hesitate to ask and I'll help you however I can.

Luke

**Comment by rafiahmad1980** [comment]
Hi Luke,

I tried creating the below PR. This is my first. So let me know if
everything is ok?

https://github.com/Pizzaface/Alexa-Chromecast-Skill-2.0/pull/16


With Regards,

Rafi Ahmad

**Comment by LukeChannings** [comment]
Fixed with PR
