### ISSUE TITLE
[Question] Necessity of MySQL?

### ISSUE THREAD

**Issue by 5punk** [Pizzaface/Alexa-Chromecast-Skill-2.0#2]
**Update**
I keep getting indentation errors in my AWS Lambda console.

---

Hi,
Love the concept, I am trying it out right now as I am writing this doubt.

Instead of a raspberry pi, I've set everything on my old spare phone.
This obviously means, I have to be really careful with and optimize my resources.

I wanted to ask you if there is a reason for using MySQL.
What is the need? And can the same thing not be achieved by keeping commands in memory?

Probably assigning each command / skill request a unique ID and resolving it later when the Youtube API replies?

Thanks.

**Comment by Pizzaface** [comment]
The MySQL Database allows the commands to be sent from the echo to the Pi. 

What do you mean by keeping the commands in memory? The commands are sent from Lambda to the MySQL Database, then are read from the database in raspberry.py, parsed, and then the command is sent VIA pychromecast.

**Comment by 5punk** [comment]
If I need to open ports and host a mysql server... Why not just host a Python Server on the Pi?
That is always listening for commands with a passphrase authentication mechanism?

**Comment by 5punk** [comment]
You had mixed spaces and tabs in your code, which caused AWS Lambda to barf, I have fixed it and made some minor changes. Can I submit a PR?

**Comment by 5punk** [comment]
`Error: There was a problem with your request: Incorrect syntax: A value may not be supplied for the slot 'query'. Occurred in sample 'sendVideoIntent send {Welcome to Hell|query} to my chromecast' on line 6. `

I keep getting the above error when trying to save my `sampl-utterances.txt` file in the developer.amazon.com console.

Help?

**Comment by Pizzaface** [comment]
Your Syntax looks correct, as you're providing a value using the | character. Perhaps try removing the line, and retyping it?

As for the server Idea, this was just a rudimentary test designed to show that Alexa could control the Chromecast through the help of a Rasp Pi. I'd love to see you fork it and see what you can do, however, this was mainly just a test.
