### ISSUE TITLE
Failed to automatically forward Port

### ISSUE THREAD

**Issue by rkeller1** [Pizzaface/Alexa-Chromecast-Skill-2.0#20]
When trying to Start the RaspberryPi Endpoint the Following Error occurs:

```
sudo bash start.sh

                    Failed to automatically forward port.
                    Please set port as an environment variable and forward manually.

```

How should i set the Port.
I can't find any place on the raspberry where i can set the env variable.

Thanks

**Comment by LukeChannings** [comment]
Hi Rob,

The skill works by running an HTTP server to accept commands for your Chromecast, this server needs to be accessible outside of your home network.

By default the skill will try to open a port automatically, using a feature called UPnP. This doesn't seem to be supported on your router, so you'll need to pick a port (something random between 1000 and 65535, higher numbers are better), and manually forward that port on your router, going to the PI address of your Raspberry Pi.

Then on the Raspberry Pi find and edit the `.env` file and add `PORT=4567` (replacing the number with your port), and run the start script again.
