### ISSUE TITLE
aws-setup.sh crashes on #!/usr/bin/bash -e

### ISSUE THREAD

**Issue by tdcrenshaw** [Pizzaface/Alexa-Chromecast-Skill-2.0#21]
On my pi B+ running raspbian, all .sh script immediately crash on the first line with the error 

`/usr/bin/env: bash -e: No such file or directory`

Changing the first line to:
`#!/usr/bin/env: bash` 
`set -e` 
fixes the issue

**Comment by jinxo13** [comment]
Changed to #!/bin/bash in latest release.
Tested as working on Raspberry PI and Ubuntu.

Recommend closing issue.
