### ISSUE TITLE
Help for install on Synology NAS with Docker

### ISSUE THREAD

**Issue by ozgurhtwg** [Pizzaface/Alexa-Chromecast-Skill-2.0#23]
Hi 
first of all, thank you so much for this solution. But i dont figured out how you skill in combination with my Synology Nas DS216+II and my Amazon Echo Plus + Docker Container.

Can you make a simple guide - step by step install on a NAS with docker? 

Thank you and sorry for my simple english skills ;)

**Comment by jinxo13** [comment]
Unfortunately I don't have a Synology NAS, although I would like one :)
Can you let me know what steps have an issue when you try and follow the install guide?

There is a ./docker-start.sh script that will create and run a docker image.
