### ISSUE TITLE
Where do videos pull from?

### ISSUE THREAD

**Issue by deathbyearthworm** [Pizzaface/Alexa-Chromecast-Skill-2.0#26]
I had a fun time getting this to work last night and got to learn about some AWS services which was pretty cool.  The control functions are working just fine but I am curious where the play video searches for video files.  Is it looking locally for UPNP sources or at something else?  Currently I use plex to stream all my videos and hoping it can be integrated but we'll see.

**Comment by Pizzaface** [comment]
There are 2 places it pulls from:
MovieDB for Trailers, and Youtube for videos.

**Comment by jinxo13** [comment]
Recommend closing
