### ISSUE TITLE
issue in final step "Listening on http://local ip:41233"

### ISSUE THREAD

**Issue by yogesh102011** [Pizzaface/Alexa-Chromecast-Skill-2.0#27]
i am done till last step..
it is stuck with "Listening on http://103.66.79.171:41233"...
its not geting subscription confirmation...
what should i do..am i making any mistakes

**Comment by gr8h** [comment]
enabled Upnp on your router for chromecast

**Comment by vrspider** [comment]
@yogesh102011 did you fix the issue by enable the upnp on your router? 
I have the same issue.

**Comment by jinxo13** [comment]
If UPNP doesn't work you can specify the port used. Then set up port forwarding through your router.
For example:
./start.sh -p 30000
./docker-start.sh -p 30000
Added to the FAQ in the readme.

Also if you use a VPN service this may prevent communication working.
