### ISSUE TITLE
YouTube Music / Spotify

### ISSUE THREAD

**Issue by FASNASTIC** [Pizzaface/Alexa-Chromecast-Skill-2.0#28]
Hey There!

Amazing skill.

A google home however can cast YouTube Music. 

This is different to regular YouTube. It’s Google’s new music service to replace Google Play Music.

Do you think you could enhance your skill to slow playing of music? 

“Alexa ask chromecast to play songs by Twenty One Pilots” for example

Or 

“Alexa ask chromecast to play EDM music”

And then it casts music from YouTube Music?

(I suppose some people may want Spotify instead but I personally use YouTube Music, plus, you already have some YouTube code worked out)

Thank you so much!

**Comment by jinxo13** [comment]
Hi @FASNASTIC, just a note that the latest release will play songs by Twenty One Pilots if you say, “Alexa ask chromecast to play songs by Twenty One Pilots”. It creates a playlist based on the search and plays through these. You can say "Alexa next" to go to the next video.

The results are from YouTube though, and not YouTube music so it's not perfect, e.g. you'll likely get repeats.
You may get a better result if you say “Alexa ask chromecast to play Twenty One Pilots playlist”

PyChromecast - which this skill uses - doesn't currently support Youtube Music.
So it is likely a bit of work to add support. Try the above in the latest release and see if it meets your needs.
