### ISSUE TITLE
issue with build.sql

### ISSUE THREAD

**Issue by caicom98** [Pizzaface/Alexa-Chromecast-Skill-2.0#3]
Got some error while importing that AUTO_INCREMENT can only be done on keys. I assigned proper primary key to the table.

CREATE TABLE IF NOT EXISTS `commands` (
`ID` int(11) NOT NULL PRIMARY KEY,
...
...
ALTER TABLE `commands`
MODIFY `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,AUTO_INCREMENT=149;

**Comment by Pizzaface** [comment]
Fixed! Thanks!
