### ISSUE TITLE
Combine with Synology NAS? Other Languages possible for voice control?

### ISSUE THREAD

**Issue by ozgurhtwg** [Pizzaface/Alexa-Chromecast-Skill-2.0#30]
Hi is there a way to install the listener on synology NAS?
If yes - can you give a short instroduction for it? THX
And can we use german voice control?

**Comment by jinxo13** [comment]
I've installed this on a Raspberry PI and on Ubuntu.
As long as you have a linux variant (which it looks like Synology does) and support for Python3 you should be able to get it to work.

Can you provide the issue encountered when following the install steps?
I'll have a look at multi-language support, I expect control is at least possible if you change the Alexa Skill JSON interaction file.
