### ISSUE TITLE
New skill json

### ISSUE THREAD

**Issue by ghost** [Pizzaface/Alexa-Chromecast-Skill-2.0#31]
Skill config seems to be not updated, please advise new config

**Comment by spectrum-art** [comment]
Through some trial and error, I got this:
`{
    "interactionModel": {
        "languageModel": {
            "invocationName": "chrome cast",
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                },
                {
                    "name": "PlayYoutubeVideo",
                    "slots": [
                        {
                            "name": "video",
                            "type": "YOUTUBE_VIDEOS"
                        }
                    ],
                    "samples": [
                        "play {video} on youtube",
                        "play {video} from youtube",
                        "play the {video}"
                    ]
                },
                {
                    "name": "PlayTrailer",
                    "slots": [
                        {
                            "name": "movie",
                            "type": "MOVIE"
                        }
                    ],
                    "samples": [
                        "play {movie} trailer",
                        "play {movie} preview",
                        "play the trailer for {movie}",
                        "play the preview for {movie}"
                    ]
                },
                {
                    "name": "PowerOff",
                    "slots": [],
                    "samples": [
                        "turn off",
                        "to turn off",
                        "power off",
                        "to power off",
                        "switch off",
                        "to switch off"
                    ]
                },
                {
                    "name": "SetVolume",
                    "slots": [
                        {
                            "name": "volume",
                            "type": "AMAZON.NUMBER"
                        }
                    ],
                    "samples": [
                        "to set volume to {volume}",
                        "volume {volume}",
                        "to turn it down to {volume}",
                        "to turn it up to {volume}"
                    ]
                },
                {
                    "name": "AMAZON.PauseIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ResumeIntent",
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "YOUTUBE_VIDEOS",
                    "values": [
                        {
                            "name": {
                                "value": "MKBHD"
                            }
                        },
                        {
                            "name": {
                                "value": "Pewdiepie"
                            }
                        },
                        {
                            "name": {
                                "value": "Iron Man Trailer"
                            }
                        },
                        {
                            "name": {
                                "value": "Casually Explained"
                            }
                        },
                        {
                            "name": {
                                "value": "EpicMealTime"
                            }
                        },
                        {
                            "name": {
                                "value": "TED"
                            }
                        },
                        {
                            "name": {
                                "value": "Saturday Night Live"
                            }
                        },
                        {
                            "name": {
                                "value": "The Verge"
                            }
                        },
                        {
                            "name": {
                                "value": "CGP Grey"
                            }
                        },
                        {
                            "name": {
                                "value": "Cheap Thrills by Sia"
                            }
                        }
                    ]
                },
                {
                    "name": "MOVIE",
                    "values": [
                        {
                            "name": {
                                "value": "The Big Lebowski"
                            }
                        }
                    ]
                }
            ]
        }
    }
}`

This includes the content from "customSlotTypes.txt" and "sample-utterances.txt". No need to add them manually.

**Comment by jinxo13** [comment]
Now resolved
