### ISSUE TITLE
Skill still working? Multidevice possible?

### ISSUE THREAD

**Issue by meia24** [Pizzaface/Alexa-Chromecast-Skill-2.0#33]
Hi,
is this skill still working?
I have multiple Chromecast Audio in different rooms, and set up some multiroom-groups in google home as well. When I am at home, I can see all devices/groups in spotify-app and amazon-music-app.
Is this supported as well and how can I configure all devices and multiroom-groups?
Thanks a lot.
Meia

**Comment by jinxo13** [comment]
I've just submitted a pull request that allows support of multiple Chromecast devices.
No multi-room group support though.
