### ISSUE TITLE
Use of AMAZON.LITERAL is deprecated

### ISSUE THREAD

**Issue by adidalax** [Pizzaface/Alexa-Chromecast-Skill-2.0#4]
Amazon has deprecated use of AMAZON.LITERAL and you wont be able to save new or update skills that use it after 02/06/2017. More details here:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/migrating-to-the-improved-built-in-and-custom-slot-types

I would guess you could probably make use of the new built-in intents they've come out with to replace some of the ones you've defined on your own:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/built-in-intent-library#video

**Comment by Pizzaface** [comment]
Hello!

I've heard about this, and while I'd love to be able to fix it, but with complications (I'm unable to reach my Raspberry Pi from the Internet), I am unable to correct this. This project has been discontinued until I can at least figure out somewhere to host a DB reliably (preferably locally). I'll be sure to update you as this goes along.

**Comment by TheFuzzball** [comment]
Hey,

I have a fork of your repo that removes the database dependency, instead relying on SNS to publish commands from the lambda function.

The client code exposes a port automatically w/ UPnP and subscribes to SNS, which might make it easier for you.

I will have a look at this issue myself later on, Amazon.LITERAL is not available in non-US locales at all, so I've removed video handling for the UK in my implementation.

https://github.com/TheFuzzball/Alexa-Chromecast-Skill-2.0

Thanks

**Comment by TheFuzzball** [comment]
I've submitted a PR that fixes this and a few other issues.

#5
