### ISSUE TITLE
What services are supported by this skill?

### ISSUE THREAD

**Issue by savahu** [Pizzaface/Alexa-Chromecast-Skill-2.0#7]
From the documentation I guess that it supports playing videos from youtube on the chromecast.
Are other services supported? 
Spotify, Plex?

**Comment by Pizzaface** [comment]
As far as I know, and this is from looking at the code, only Youtube is supported. This is more a limitation by pychromecast.

**Comment by savahu** [comment]
I understand.. Unfortunately I can't get your scripts to work but I will close this issue and post in the other one.
Thanks
