### ISSUE TITLE
Instruction suggestions

### ISSUE THREAD

**Issue by NathanMaton** [Pizzaface/Alexa-Chromecast-Skill-2.0#8]
In going through the skill creation a lot of errors were thrown that weren't mention in the instructions. Specifically consider adding:
-Instructions on custom slot type - had to dig around commits to see YouTube needed a custom slot
-Movie didn't have any custom slot file like YouTube did, I had to make one up to get through prompts

**Comment by LukeChannings** [comment]
Added `MOVIE` to customSlotTypes.
